### ISSUE TITLE
Just report status

### ISSUE THREAD

**Issue by frankbolviken** [ArcBees/teamcity-plugins#28]
We have a setup which consists of 3 projects, which are combined together into 1 artifact.
The setup in Teamcity is:

Build client
Build x                        superjob
Build y

The superjob listenes for triggers on all of the dependencies, and sets up build if changes are made.
In this case the pull request trigger won't work, as we have intact 3 differen t VCS roots, and therefor you cannot specify which branch the pull request is triggered on.

So, would be awesome if you could just have a build feature like the Status report to Stash plugin, which only reports the status of the build to the pull request, and skip the whole trigger part of it?

**Comment by meriouma** [comment]
Fixed by #48
