### ISSUE TITLE
GsonDateTypeAdapter isn't thread safe

### ISSUE THREAD

**Issue by wgauvin** [ArcBees/teamcity-plugins#33]
In the GsonDateTypeAdapter class, the DateFormat's are private static final.  DateFormat / SimpleDataFormat's are not thread safe (check the JavaDoc of both Java classes - http://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html).

You need to explicitly synchronise on these class variables or you need to create a new instance of the DataFormat in the deserialise method.

**Comment by meriouma** [comment]
Thanks for reporting. I believe #34 should be sufficient, what do you think?
