### ISSUE TITLE
Plugin not working in teamcity

### ISSUE THREAD

**Issue by mcmug8** [ArcBees/teamcity-plugins#36]
Hi,

I tried install this plugin in teamcity. For some reason, I can't get the trigger to set to bitbucket pull request seems like plugin is not working correctly. Any idea?

Regards,
Tim

**Comment by olafleur** [comment]
Could you define a little bit more what you tried, what you did and what you expect the result to be?

**Comment by mcmug8** [comment]
Hi,
Yeah, I tried zip the project file and installed as a plugin in teamcity somehow I can't get it to work. Any idea, how I can install this as a plugin in teamcity?

Thanks,
Tim

**Comment by meriouma** [comment]
You should be able to install it following this guide : https://confluence.jetbrains.com/display/TCD9/Installing+Additional+Plugins
