### ISSUE TITLE
Doesn't seem to be working.

### ISSUE THREAD

**Issue by bryansoto** [ArcBees/teamcity-plugins#40]
I've got the plugin installed and configured the trigger.

This error shows up in the ~~console~~ log file though and the number of tests run doesn't increase, even though the pull request adds new ones.

It seems to be reading the pull request information as it does find PullRequestBranchName in the error message.

It's a binary, so I'll see if I can verify that the code from the branch is built.

```
Apr 19, 2016 9:23:11 AM com.arcbees.pullrequest.PullRequestStatusHandler handle
INFO: Handling build status - Build Status: FINISHED, Branch: [PullRequestBranchName], isSuccessful: true
Apr 19, 2016 9:23:11 AM com.arcbees.pullrequest.PullRequestsBuildListener$2 run
SEVERE: Error updating pull request status.
com.arcbees.vcs.util.UnexpectedHttpStatusException: Failed to complete request. Status: HTTP/1.1 404 NOT FOUND
{"error": {"message": "Changeset not found."}}
	at com.arcbees.vcs.AbstractVcsApi.doExecuteRequest(AbstractVcsApi.java:128)
	at com.arcbees.vcs.AbstractVcsApi.executeRequest(AbstractVcsApi.java:51)
	at com.arcbees.vcs.bitbucket.BitbucketApi.updateStatus(BitbucketApi.java:140)
	at com.arcbees.pullrequest.PullRequestStatusHandler.updateStatus(PullRequestStatusHandler.java:129)
	at com.arcbees.pullrequest.PullRequestStatusHandler.handle(PullRequestStatusHandler.java:85)
	at com.arcbees.pullrequest.PullRequestsBuildListener$2.run(PullRequestsBuildListener.java:87)
	at jetbrains.buildServer.util.ExceptionUtil$1.run(ExceptionUtil.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bryansoto** [comment]
Ok, this particular build is configured to produce an artifact. I downloaded the artifact and verified the code from the pull request is not present in it.

I'm assuming that the code from the pull request should be present, but it's not documented, so I may be wrong.

**Comment by meriouma** [comment]
I'm not sure what is the issue you have exactly? Can you give more details on what you're trying to achieve and what's your setup? Also is it a git repo?

**Comment by bryansoto** [comment]
It's a git repo.

I'm trying to use your plugin to compile pull requests from Bitbucket.

I have pull requests that add new tests and new classes.

When compiling the "pull request", the plugin doesn't run the new tests; only the tests from the main branch of the repo. The build configuration is set to produce an artifact. The artifact does not contain the new classes.

To sum up, the plugin doesn't seem to be compiling the pull request, only the main branch.

It's also giving an error message (see my first comment) when trying to post the status. To me, that's secondary as, again, it doesn't seem to actually be compiling the pull request so saying it builds successfully would be misleading.

Hopefully this is enough detail?

**Comment by meriouma** [comment]
What's your VCS branch specification?

**Comment by bryansoto** [comment]
+:refs/heads/*

**Comment by meriouma** [comment]
Are you using you own Bitbucket server or Bitbucket Cloud?

**Comment by bryansoto** [comment]
Bitbucket cloud.

**Comment by meriouma** [comment]
Hmm that's weird.. I'm running out of ideas.. Do you mind posting a screenshot of the plugin's settings?

**Comment by bryansoto** [comment]
![2016-05-24 07_19_35-dwmapi configuration teamcity - internet explorer](https://cloud.githubusercontent.com/assets/857543/15507647/4c0d88ca-2181-11e6-873d-012118afaed0.png)

I took out a couple of pieces of info since it's for work. Sorry it that makes it less useful.

Does the plugin have any requirements or make any assumptions? Or could you point me to the relevant file(s)? I'd really like for this to work. :)

**Comment by meriouma** [comment]
And I guess your default VCS branch is development too?

As far as I can tell, you setup meet the requirements, unless the owner or repository is wrong. I never had the "Changeset not found." issue. It seems the commit hash TeamCity uses to build doesn't exist on the remote, which doesn't really makes sense

**Comment by bryansoto** [comment]
Does the plugin work if the pull request comes from a forked repository or does it assume that the branch exists on the same repo?

**Comment by meriouma** [comment]
Ah! The plugin definitely won't work on a forked repo, sorry!

**Comment by bryansoto** [comment]
I'm not familiar with the BitBucket API. When you say the plugin definitely won't work on a forked repo, is that due to a limitation with the API or is it just because that wasn't what your requirements were?

Like I said, I'd really like for this to work and if the API supports it, I might give it a try. The downside is I've never done anything with the BitBucket API or written a TeamCity plugin. :)

Feel free to close this since it's not a bug. Thanks for the help.

**Comment by meriouma** [comment]
I was saying that mostly because it wasn't what we needed. I haven't given it much thoughts, but I'm not sure if the API would support it. I haven't found much information on the subject either. 
It does works on GitHub though, because it handles PRs differently than Bitbucket.
