### ISSUE TITLE
Stuck with pending in TC

### ISSUE THREAD

**Issue by beersky** [ArcBees/teamcity-plugins#52]
Hi and thanks for the plugin.

When I do a pull request in BitBucket cloud my Team City build only displays pending in status so I wonder if anyone got any tip for getting it to trigger. I have setup the trigger like the wiki-docs suggested.

**Comment by meriouma** [comment]
Hi @beersky,
Are you saying the pull request queues a build but never actually build, or the commits only shows in pending commits?

What are the source and target branches of your PR?
What do you have set as the Base branch setting?

**Comment by beersky** [comment]
Hi sorry for late response.

Yes, they got stuck at pending but never built the stuff.

I figured it out, I had messed up the settings.
