### ISSUE TITLE
Can't download Bitbucket Pull Requests Plugin

### ISSUE THREAD

**Issue by velika12** [ArcBees/teamcity-plugins#59]
Hi, I'm trying to download the plugin using the link from your wiki but the server doesn't respond. Maybe you have moved the file somewhere without updating the link?

**Comment by starmandeluxe** [comment]
Same problem. Please fix it so we can use it.

**Comment by Durgaprasad-Budhwani** [comment]
Same problem, can you please fix it?

**Comment by meriouma** [comment]
Sorry for the delay, I created a [pre-release](https://github.com/ArcBees/teamcity-plugins/releases/tag/pullrequest-20172603195632) and added the binaries
