### ISSUE TITLE
Password must be specified

### ISSUE THREAD

**Issue by redhandpl** [ArcBees/teamcity-plugins#68]
Hi,

On TeamCity 2019.1 there is a problem with this plugin. When creating new Pull Requests trigger an error occurs saying that "Password must be specified". But it is specified.
![pr_trigger](https://user-images.githubusercontent.com/1423024/60091727-903d8800-9745-11e9-9d58-c0c64e684b54.png)

On TC 2018.x it worked.

**Comment by redhandpl** [comment]
This PR fixed it.
https://github.com/ArcBees/teamcity-plugins/pull/69

**Comment by peter-majeed** [comment]
Thanks for the PR! I end up manually changing the input type to `password` as a manual workaround, given that the PR hasn't been merged to master yet.
